version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=1234
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=1234
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana-k6
    ports:
      - "8080:3000" # Grafana 대시보드: http://localhost:8080
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=1234
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./k6:/scripts
    entrypoint: ["k6", "run", "--out", "influxdb=http://influxdb:8086/k6", "/scripts/test.js"]
    depends_on:
      - influxdb
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring: