services:

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      - POSTGRESQL_USER=${PROD_DB_USERNAME}
      - POSTGRESQL_PASSWORD=${PROD_DB_PASSWORD}
      - POSTGRESQL_URL=jdbc:postgresql://${PROD_DB_ENDPOINT}:5432/${PROD_DB_NAME}
    networks:
      - mumuk_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  mumuk_network:
    driver: bridge