version: '3'

services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./k6:/scripts
    entrypoint: [ "k6", "run", "/scripts/test.js" ]
    networks:
      - monitoring

networks:
  monitoring: