services:

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    image: parkmineum/mumuk-backend:v1.0.0
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRESQL_USER=mumuk
      - POSTGRESQL_PASSWORD=park9368!
      - POSTGRESQL_URL=jdbc:postgresql://mumuk-rds.cvg4ai0yyl17.ap-northeast-2.rds.amazonaws.com:5432/mumuk
    networks:
      - mumuk_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "90:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.mumuk.site:/etc/letsencrypt/live/api.mumuk.site:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
    environment:
      - TZ=Asia/Seoul
    networks:
      - mumuk_network
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-kf", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mumuk_network:
    driver: bridge