spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    format_sql: true

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379


jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}    # 1시간
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}  # 2주

app:
  env: local

kakao:
  redirect-uri: http://localhost:8080/login/oauth2/code/kakao    # 인가 코드

naver:
  login:
    client-id: ${NAVER_CLIENT_ID}
    secret-key: ${NAVER_SECRET_KEY}
    redirect-uri: http://localhost:8080/login/oauth2/code/naver      # 인가 코드
  blog:
    client-id: ${NAVER_BLOG_CLIENT_ID}
    secret-key: ${NAVER_BLOG_SECRET_KEY}
    base-url: https://openapi.naver.com/v1/search/blog.json
  clova:
    ocr:
      invoke-url: ${NAVER_CLOVA_INVOKE_URL}
      secret-key: ${NAVER_CLOVA_SECRET_KEY}


colsms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
    sender: 01087164428

openai:
  api:
    key: ${OPEN_AI_KEY}
    url: https://api.openai.com/v1
    model: gpt-4o-mini


management:
  endpoints:
    web:
      exposure:
        include: prometheus