spring:
  datasource:
    url: ${LOCAL_DB_URL:jdbc:postgresql://localhost:5432/mumuk_db}
    username: ${LOCAL_DB_USERNAME:postgres}
    password: ${LOCAL_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379


jwt:
  secret: ${JWT_SECRET_KEY:dummy-jwt-secret-key-very-long-and-secure}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:3600}    # 1시간
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:1209600}  # 2주

app:
  env: local

kakao:
  native-app-key: ${KAKAO_SECRET_KEY:dummy-kakao-app-key}
  redirect-uri: http://localhost:8080/login/oauth2/code/kakao    # 인가 코드
  token-uri: https://kauth.kakao.com/oauth/token      # 토큰 발급 요청
  user-info-uri: https://kapi.kakao.com/v2/user/me    # 유저 정보 조회

naver:
  login:
    client-id: ${NAVER_CLIENT_ID:dummy-naver-client-id}
    secret-key: ${NAVER_SECRET_KEY:dummy-naver-secret-key}
    redirect-uri: http://localhost:8080/login/oauth2/code/naver      # 인가 코드
    token-uri: https://nid.naver.com/oauth2.0/token       # 토큰 발급 요청
    user-info-uri: https://openapi.naver.com/v1/nid/me    # 유저 정보 조회
  blog:
    client-id: ${NAVER_BLOG_CLIENT_ID}
    secret-key: ${NAVER_BLOG_SECRET_KEY}
    base-url: https://openapi.naver.com/v1/search/blog.json


colsms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
    sender: 01087164428

openai:
  api:
    key: ${OPEN_AI_KEY:dummy-openai-key}
    url: https://api.openai.com/v1
    model: gpt-4o-mini


management:
  endpoints:
    web:
      exposure:
        include: prometheus