spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379

naver:
  login:
    redirect-uri: ${NAVER_PROD_REDIRECT_URI}

kakao:
  native-app-key: ${KAKAO_NATIVE_APP_KEY}
  redirect-uri: ${KAKAO_PROD_REDIRECT_URI}
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me