spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_ENDPOINT}:5432/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate