spring:
  datasource:
    url: jdbc:postgresql://mumuk-rds.cvg4ai0yyl17.ap-northeast-2.rds.amazonaws.com:5432/mumuk
    username: mumuk
    password: park9368!
#    url: ${POSTGRESQL_URL}
#    username: ${POSTGRESQL_USER}
#    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  env: prod

kakao:
  native-app-key: ${KAKAO_SECRET_KEY}
  redirect-uri: https://api.mumuk.site/login/oauth2/code/kakao
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me


jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}    # 1시간
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}  # 2주

  # ec2 서버에서 작동하는지 확인할 수 없어 우선은 주석 처리해두었습니다.
  #data:
  #  redis:
  #    host: ${PROD_DB_ENDPOINT}
  #    port: 6379
  #    password: ${PROD_REDIS_PASSWORD}


