global:
  scrape_interval: 15s       # 매트릭 수집 주기

scrape_configs:
  - job_name: 'springboot-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'prometheus-self'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

  - job_name: 'rds-postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]