global:
  scrape_interval: 15s       # 매트릭 수집 주기

scrape_configs:
  - job_name: 'springboot-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'prometheus-self'
    static_configs:
      - targets: [ 'localhost:9090' ]
