server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs: []

    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    relabel_configs:
      # backend 컨테이너만 수집
      - source_labels: [__meta_docker_container_name]
        regex: backend
        action: keep

      # 라벨 추가 (최소 하나 이상)
      - source_labels: [__meta_docker_container_name]
        target_label: container

      # 실제 로그 파일 경로 라벨로 추가 (stream 식별용 필수)
      - source_labels: [__meta_docker_container_logpath]
        target_label: __path__
