server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: /backend
        action: keep

      - source_labels: [ __meta_docker_container_name ]
        target_label: container
      - source_labels: [ __meta_docker_image_name ]
        target_label: image

      - source_labels: [ __meta_docker_container_logpath ]
        target_label: __path__
        replacement: /var/lib/docker/containers/${1}/**.log

    pipeline_stages:
      - docker: {}
