server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend-container-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
    relabel_configs:
      - source_labels: [__path__]
        regex: '.*/([a-f0-9]{64})-json.log'
        target_label: container_id

      - source_labels: [container_id]
        target_label: container_name
        replacement: backend

      - source_labels: [container_name]
        regex: backend
        action: keep
