name: MuMuk CI/CD Workflow with Gradle

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Create application.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application-prod.yml
        shell: bash

      - name: Create nginx.conf
        run: |
          mkdir -p ./nginx
          echo "${{ secrets.NGINX_CONF }}" | base64 -d > ./nginx/nginx.conf

      - name: Build with Gradle without tests
        run: ./gradlew clean bootJar -x test

      - name: Debug SSH Key (unmasked)
        run: |
          echo "${{ secrets.NCP_SSH_KEY }}" | awk '{print $0}' > ssh_key_debug.txt
          head -n 5 ssh_key_debug.txt


      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          key: ${{ secrets.NCP_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/root/UMC-MuMuk/build/libs/"
  CD:
    needs: CI
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          key: ${{ secrets.NCP_SSH_KEY }}
          script: |
            cd /root/UMC-MuMuk

            sudo chmod -R u+w ./nginx

            sudo docker-compose down

            git fetch origin
            git reset --hard origin/main

            ./gradlew clean bootjar

            if [ "$(sudo docker ps -qa)" ]; then
              sudo docker ps -qa | xargs -r sudo docker rm -f
            fi
            sudo docker rmi $(sudo docker images -q) || true

            sudo docker-compose up --build -d
            sudo docker image prune -f
