name: MuMuk CI/CD Workflow with Gradle

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_NAME: mumuk-backend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Create application.yml
        run: |
          mkdir -p docker-context
          echo "${{ secrets.APPLICATION }}" > docker-context/application-prod.yml
        shell: bash

      - name: Build JAR
        run: ./gradlew clean bootJar -x test

      - name: Copy JAR to Docker context
        run: |
          cp build/libs/*.jar docker-context/app.jar

      - name: Check built JAR
        run: |
          echo "Listing built JARs:"
          ls -lh build/libs
          echo "Checking file type:"
          file build/libs/*.jar

      - name: Copy JAR to Docker context
        run: |
          mkdir -p docker-context
          cp build/libs/*.jar docker-context/app.jar

      - name: Check copied app.jar
        run: |
          echo "Checking copied app.jar:"
          ls -lh docker-context
          file docker-context/app.jar

      - name: Verify copied JAR version
        run: |
          strings docker-context/app.jar | grep -iE "version|build|timestamp|MuMuk"

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image with SHA tag
        run: docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

  CD:
    needs: CI
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/BE

            sed -i '/^IMAGE_TAG=/d' .env
            echo "IMAGE_TAG=${{ github.sha }}" >> .env

            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mumuk-backend:$IMAGE_TAG
            
            docker compose down
            docker compose rm -f backend
            docker compose up -d --force-recreate

            docker image prune -f